parameters:
  "service-dir":
    default: "sdk/microsoft.app"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/http-server-csharp"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DynamicSessions.json"
  "@typespec/http-server-csharp":
    emitter-output-dir: "{output-dir}/server/generated"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
